version: '3.9'

networks:
  dev:
    driver: bridge

services:
  httpserver:
    image: nnatalia/iot:httpserver
    depends_on:
      - serverdb
      - authdb
    container_name: httpserver
    build:
      context: ./HttpServer
      dockerfile: Dockerfile
    environment:
      - 'ASPNETCORE_URLS=Development'
    ports:
      - '80:5000'
    networks:
      - dev

  mqttserver:
    image: nnatalia/iot:mqttserver
    container_name: mqttserver
    build:
      context: ./MqttServer
      dockerfile: Dockerfile
    ports:
      - '1883:1883'
    networks:
      - dev

  serverdb:
    image: nnatalia/iot:postgres
    container_name: serverdb
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=ServerDb'
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - app_data_server:/var/lib/postgresql/data
    networks:
      - dev
  
  authdb:
    image: postgres:latest
    container_name: authdb
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=AuthDb'
    ports:
      - '5434:5432'
    restart: always
    volumes:
      - app_data_auth:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data_server:
  app_data_auth: